### PR TITLE
fix buffer length var in socket_write()

### PR DESCRIPTION
**Pull request by bjnhur**
Related to Issue #41 
Fix buf length logic in socket_write() on adafruit_wiznet5k/adafruit_wiznet5k.py
Would you pls check this commit @brentru ?

### CODE REVIEW

**Comment by bjnhur** [comment]
Build CI fail, but it's not my fixes.
I try fixing the following, also fails. pls check the following errors.

************* Module wiznet5k_wsgiserver_test
examples/wiznet5k_wsgiserver_test.py:35:12: W0621: Redefining name 'i2c' from outer scope (line 70) (redefined-outer-name)
examples/wiznet5k_wsgiserver_test.py:37:4: W0621: Redefining name 'mac' from outer scope (line 72) (redefined-outer-name)
examples/wiznet5k_wsgiserver_test.py:49:8: W0622: Redefining built-in 'bytes' (redefined-builtin)
examples/wiznet5k_wsgiserver_test.py:116:8: W0613: Unused argument 'request' (unused-argument)
examples/wiznet5k_wsgiserver_test.py:23:0: W0611: Unused import time (unused-import)
examples/wiznet5k_wsgiserver_test.py:23:0: C0411: standard import "import time" should be placed before "import board" (wrong-import-order)
examples/wiznet5k_wsgiserver_test.py:29:0: C0411: third party import "from adafruit_wsgi.wsgi_app import WSGIApp" should be placed before "from adafruit_wiznet5k.adafruit_wiznet5k import WIZNET5K" (wrong-import-order)

**Comment by brentru** [comment]
> Build CI fail, but it's not my fixes. I try fixing the following, also fails. pls check the following errors.

Ok, likely the version of PyLint has been updated on our CI and it's throwing errors due to new rules(@kattni - could you confirm this is what occurred?). 

Do you have cycles to fix these linter errors and commit to this branch? Otherwise, I can fix and commit to the branch as well.

I'd like to merge this fix in - thank you for finding it - let me know what you want to do and we'll do it.

**Comment by kattni** [comment]
@brentru I can't get the check failure to load when I click details, so I can't verify the list of failures. This library uses `pre-commit` meaning the Pylint version is pinned, so Pylint updating out from under you is not possible at this time. I don't know have an answer to why things here would suddenly start failing.

**Comment by brentru** [comment]
Yeah, the actions service is degraded currently. I'll ping you when I have a better answer/can check it.

**Comment by bjnhur** [comment]
> > Build CI fail, but it's not my fixes. I try fixing the following, also fails. pls check the following errors.
> 
> Ok, likely the version of PyLint has been updated on our CI and it's throwing errors due to new rules(@kattni - could you confirm this is what occurred?).
> 
> Do you have cycles to fix these linter errors and commit to this branch? Otherwise, I can fix and commit to the branch as well.
> 
> I'd like to merge this fix in - thank you for finding it - let me know what you want to do and we'll do it.

@brentru I don't think I can handle these linter errors..., I need you to handle this. Thx :)

**Review by FoamyGuy — APPROVED** [review]
I merged main and it got this passing CI. 

Changes look good to me. Tested successfully simpletest and wsgiserver test using feather rp2040 and Ethernet featherwing.

**Pull request merged**
