### PR TITLE
Remove `assert`'s

### LINKED ISSUE #83: Don't use asserts for necessary code
Using any nonzero `-O` level with mpy-cross causes Python `assert` statements to not be included.

This is not compatible with the way that wiznet5k uses assert statements, because it depends on the assert statement's expression being evaluated for correct operation. For example,
```python
assert self._w5100_init() == 1, "Failed to initialize WIZnet module."
```

Because Adafruit's circuitpython-build-tools never specify a `-O` level, this problem will not affect mpy files we generate or ship to users.

However, fixing the way asserts are used (probably by replacing them with a variation on `if not condition: raise RuntimeError("message")` in the case where the side-effect of the expression is required) would be welcome from contributors.

If you agree with this analysis, I recommend either re-titling and updating the initial comment on this issue, or closing it and opening a fresh one to reflect the conclusion.

_Originally posted by @jepler in https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/issues/67#issuecomment-1359379605_

### PR DESCRIPTION
**Pull request by bill88t**
This is following #67 and is independent to it.
Closes #83 .

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thanks! These are not really assertion failures, in many cases, but `RuntimeError`s or similar, because they do not reflect an error in the code (which is what assertions are checking). So could you consider what exception you would like to be raised for these? The wifi exceptions for similar problems could be used as a model, if they make sense.

**Comment by bill88t** [comment]
This was a minimally invasive pr, however since requested, I will update the exceptions based on `wifi`.

**Review by dhalbert — APPROVED** [review]
These changes look good to me! The exceptions chosen are appropriate.

**Comment by bill88t** [comment]
Updated to fix conflicts & to switch `w5100_init` to `w5xxx_init`

**Comment by tekktrik** [comment]
Is this good to go now that changes from `main` are merged?

**Comment by bill88t** [comment]
Yep, its done.

**Pull request merged**
