### PR TITLE
Add Adafruit_CircuitPython_Requests Compatibility

### PR DESCRIPTION
**Pull request by brentru**
* Updated `_socket` for compatibility with `Adafruit_CircuitPython_Requests` library
* Added: NEW EXAMPLE to post to Adafruit IO using Requests
* Fixed: `_socket` `readline` not parsing multiple lines correctly
* Fixed: `_socket`'s `recv` for UDP packets
* Fixed: `adafruit_wiznet5k_dhcp` w.r.t incorrect address parsing
* Updated `wiznet5k_simpletest` to mirror https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/master/examples/esp32spi_simpletest.py
* sprinkled some `gc.collect()`'s where i could in `adafruit_wiznet5k_dhcp`

        master.:
        GC Allocated:  34528
        GC Freed:  125088
        P/R
        GC Allocated:  33168
        GC Freed:  126448

---
Tested on: `Adafruit CircuitPython 5.0.0-beta.5 on 2020-02-05; Adafruit Feather M4 Express with samd51j19`

Test output: `wiznet5k_simpletest`
```
code.py output:
Wiznet5k WebClient Test
Chip Version: w5500
MAC Address: ['0xde', '0xad', '0xbe', '0xef', '0xfe', '0xed']
My IP address is: SNIP!
IP lookup adafruit.com: 104.20.39.240
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
This is a test of Adafruit WiFi!
If you can read this, its working :)

----------------------------------------

Fetching json from http://api.coindesk.com/v1/bpi/currentprice/USD.json
----------------------------------------
{'time': {'updated': 'Mar 4, 2020 15:46:00 UTC', 'updatedISO': '2020-03-04T15:46:00+00:00', 'updateduk': 'Mar 4, 2020 at 15:46 GMT'}, 'disclaimer': 'This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org', 'bpi': {'USD': {'code': 'USD', 'description': 'United States Dollar', 'rate_float': 8732.83, 'rate': '8,732.8350'}}}
----------------------------------------
Done!
```

Test: `requests_simpletest.py` (https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/master/examples/requests_simpletest.py), modified for eth. object instead of esp32spi object.

```
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
Text Response:  This is a test of Adafruit WiFi!
If you can read this, its working :)

----------------------------------------
Fetching JSON data from http://httpbin.org/get
----------------------------------------
JSON Response:  {'url': 'http://httpbin.org/get', 'headers': {'User-Agent': 'Adafruit CircuitPython', 'Host': 'httpbin.org', 'X-Amzn-Trac
e-Id': 'Root=1-5e5fce66-ca1da55eca173bfe7905aabe'}, 'args': {}, 'origin': '73.38.253.75'}
----------------------------------------
POSTing data to http://httpbin.org/post: 31F
----------------------------------------
Data received from server: 31F
----------------------------------------
POSTing data to http://httpbin.org/post: {'Date': 'July 25, 2019'}
----------------------------------------
JSON Data received from server: {'Date': 'July 25, 2019'}
----------------------------------------
```

### CODE REVIEW

**Comment by anecdata** [comment]
Not sure if I've pieced together all the right things, but...

`Adafruit CircuitPython 5.0.0-beta.5 on 2020-02-05; Adafruit Feather M4 Express with samd51j19`
+
CP Library bundle: `adafruit-circuitpython-bundle-5.x-mpy-20200206`
+
brentru / Adafruit_CircuitPython_Wiznet5k library: [https://github.com/brentru/Adafruit_CircuitPython_Wiznet5k/tree/update-for-requests](https://github.com/brentru/Adafruit_CircuitPython_Wiznet5k/tree/update-for-requests)

Running example code from
[https://github.com/brentru/Adafruit_CircuitPython_Wiznet5k/blob/update-for-requests/examples/wiznet5k_simpletest.py](https://github.com/brentru/Adafruit_CircuitPython_Wiznet5k/blob/update-for-requests/examples/wiznet5k_simpletest.py)

```code.py output:
Wiznet5k WebClient Test
Traceback (most recent call last):
  File "code.py", line 18, in <module>
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 186, in __init__
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 200, in set_dhcp
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k_dhcp.py", line 361, in request_dhcp_lease
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k_dhcp.py", line 210, in send_dhcp_message
NotImplementedError: array/bytes required on right side```

**Comment by anecdata** [comment]
With commit `7db5a2c` trace is now: ```Traceback (most recent call last):
  File "code.py", line 17, in <module>
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 186, in __init__
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 200, in set_dhcp
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k_dhcp.py", line 359, in request_dhcp_lease
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k_dhcp.py", line 322, in parse_dhcp_response
IndexError: bytes index out of range``` (all preceding is same)

**Comment by brentru** [comment]
@anecdata Could you test breaking parsing the packet on the padding opt, added in #30c9f0a?

**Comment by anecdata** [comment]
...
```
This is a test of Adafruit WiFi!
If you can read this, its working :)
```
...
```
{'time': {'updated': 'Mar 5, 2020 02:42:00 UTC', 'updatedISO': '2020-03-05T02:42:00+00:00', 'updateduk': 'Mar 5, 2020 at 02:42 GMT'}, 'disclaimer': 'This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org', 'bpi': {'USD': {'code': 'USD', 'description': 'United States Dollar', 'rate_float': 8938.09, 'rate': '8,938.0967'}}}
----------------------------------------
Done!



Press any key to enter the REPL. Use CTRL-D to reload.
```

**Comment by anecdata** [comment]
Most of the time it works, but I do get this occasionally:
```
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
Traceback (most recent call last):
  File "code.py", line 178, in <module>  # my gist
  File "adafruit_requests.py", line 280, in get
  File "adafruit_requests.py", line 242, in request
  File "adafruit_requests.py", line 199, in request
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k_socket.py", line 158, in send
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 694, in socket_write
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 749, in _write_sntx_wr
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 822, in _write_socket
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 442, in write
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 439, in write
ValueError: bytes value out of range
```

**Comment by anecdata** [comment]
There's also this when trying HTTPS, not sure if it's a limitation of the board:
`AttributeError: 'WIZNET5K' object has no attribute 'TLS_MODE'`

**Comment by brentru** [comment]
@anecdata  CircuitPython doesn't have a native SSL client, nina-fw uses a mbedTLS implementation. I'll add a commit to make that error more readable.

> Most of the time it works, but I do get this occasionally:
I haven't been able to replicate this.

**Comment by anecdata** [comment]
Looks good to me. Got the friendlier AssertionError for TLS. Other errors are rare, seem similar to communication glitches on esp. I'd expect to catch exceptions and handle in user code. If any patterns emerge, I'll report back.

CircuitPython takes flight on Cat5e.

**Comment by brentru** [comment]
@jerryneedell  seems it's closing the socket immediately after opening it, which causes the failure.

Your trace:
```
*** Opening socket 0
w5k socket begin, protocol=33, port=80, ip=104.236.193.178
*** Closing socket #0
Traceback (most recent call last):
```

My trace: 
```
*** Get socket
Allocated socket #0:1024
*** Connecting: Socket# 0, conn_mode: 33
*** Opening socket 0
w5k socket begin, protocol=33, port=80, ip=104.236.193.178
* socket_available called with protocol 33
* socket_available called with protocol 33
* socket_available called with protocol 33
* socket_available called with protocol 33
* socket_available called with protocol 33
Bytes avail. on sock:  310
         * Processing 310 bytes of data
----------------------------------------
*** Closing socket #0
This is a test of Adafruit WiFi!
```

**Comment by brentru** [comment]
@jerryneedell Figured it out - code was _sometimes_ re-using a registered port number for TCP sockets, which was causing the server to send an ACK-RST back to the device disconnecting it. 406c7fb switches to randomly assigned dynamic port numbers.

**Comment by jerryneedell** [comment]
tried with same result -- updated gist https://gist.github.com/jerryneedell/48367e4c0cc05fe11d4ce2be4d5ac104

**Comment by brentru** [comment]
@jerryneedell  Could you test again?

**Comment by jerryneedell** [comment]
still not working - 
```soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Wiznet5k WebClient Test
Chip Version: w5500
MAC Address: ['0xde', '0xad', '0xbe', '0xef', '0xfe', '0xed']
My IP address is: 192.168.2.32
IP lookup adafruit.com: 104.20.39.240
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
Traceback (most recent call last):
  File "code.py", line 30, in <module>
  File "adafruit_requests.py", line 283, in get
  File "adafruit_requests.py", line 245, in request
  File "adafruit_requests.py", line 194, in request
  File "adafruit_wiznet5k/adafruit_wiznet5k_socket.py", line 149, in connect
  File "adafruit_wiznet5k/adafruit_wiznet5k.py", line 515, in socket_connect
RuntimeError: Failed to establish connection.



Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-alpha.4-127-g22b7050c4 on 2019-10-03; Adafruit Feather M4 Express with samd51j19
```

**Comment by jerryneedell** [comment]
hmmm --- FYI -- the example/library from the master branch is also not workig for me -- it just hangs after displaying the IP address

**Comment by jerryneedell** [comment]
it is working for me now 
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-alpha.4-127-g22b7050c4 on 2019-10-03; Adafruit Feather M4 Express with samd51j19
>>> 
>>> 
>>> import nodebug
Wiznet5k WebClient Test
Chip Version: w5500
MAC Address: ['0xde', '0xad', '0xbe', '0xef', '0xfe', '0xed']
My IP address is: 192.168.2.32
IP lookup adafruit.com: 104.20.39.240
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
This is a test of Adafruit WiFi!
If you can read this, its working :)

----------------------------------------

Fetching json from http://api.coindesk.com/v1/bpi/currentprice/USD.json
----------------------------------------
{'time': {'updated': 'Mar 5, 2020 21:48:00 UTC', 'updatedISO': '2020-03-05T21:48:00+00:00', 'updateduk': 'Mar 5, 2020 at 21:48 GMT'}, 'disclaimer': 'This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org', 'bpi': {'USD': {'code': 'USD', 'description': 'United States Dollar', 'rate_float': 9125.52, 'rate': '9,125.5233'}}}
----------------------------------------
Done!
```

**Comment by brentru** [comment]
Tested working on Metro M4 Express w/Ethernet Shield (https://www.adafruit.com/product/2971) 
`Adafruit CircuitPython 5.0.0 on 2020-03-02; Adafruit Metro M4 Express with samd51j19`
```
Wiznet5k WebClient Test
Chip Version: w5500
MAC Address: ['0xde', '0xad', '0xbe', '0xef', '0xfe', '0xed']
My IP address is:
IP lookup adafruit.com: 104.20.39.240
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
This is a test of Adafruit WiFi!
If you can read this, its working :)

----------------------------------------

Fetching json from http://api.coindesk.com/v1/bpi/currentprice/USD.json
----------------------------------------
{'time': {'updated': 'Mar 6, 2020 14:33:00 UTC', 'updatedISO': '2020-03-06T14:33:00+00:00', 'updateduk': 'Mar 6, 2020 at 14:33 GMT'}, 'disclaimer': 'This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org', 'bpi': {'USD': {'code': 'USD', 'description': 'United States Dollar', 'rate_float': 9115.01, 'rate': '9,115.0117'}}}
----------------------------------------
Done!
```

**Pull request merged**
