### PR TITLE
Convert to SocketPool

### PR DESCRIPTION
**Pull request by justmobilize**
For use with: https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/pull/11

Converting from the old `adafruit_wiznet5k/adafruit_wiznet5k_socket.py` to `adafruit_wiznet5k/adafruit_wiznet5k_socketpool.py` to remove `set_interface` and work more like a built-in SocketPool.

This also allows one to use multiple WIZNET5K boards at the same time.

General example:
```py
import board
import busio
import digitalio
import adafruit_requests
from adafruit_wiznet5k.adafruit_wiznet5k import WIZNET5K
import adafruit_wiznet5k.adafruit_wiznet5k_socketpool as socketpool

TEXT_URL = "http://wifitest.adafruit.com/testwifi/index.html"

cs = digitalio.DigitalInOut(board.D10)
spi_bus = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
radio = WIZNET5K(spi_bus, cs)
pool = socketpool.SocketPool(radio)
requests = adafruit_requests.Session(pool)
print(requests.get(TEXT_URL).text)
```

or with the new `ConnectionManager`
```py
import board
import busio
import digitalio
import adafruit_connection_manager
import adafruit_requests
from adafruit_wiznet5k.adafruit_wiznet5k import WIZNET5K
from adafruit_wiznet5k import adafruit_wiznet5k_socketpool

TEXT_URL = "http://wifitest.adafruit.com/testwifi/index.html"

cs = digitalio.DigitalInOut(board.D10)
spi_bus = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
radio = WIZNET5K(spi_bus, cs)
pool = adafruit_connection_manager.get_radio_socketpool(radio)
assert isinstance(pool, adafruit_wiznet5k_socketpool.SocketPool)
requests = adafruit_requests.Session(pool)
print(requests.get(TEXT_URL).text)
```

### CODE REVIEW

**Comment by justmobilize** [comment]
@anecdata re-done with all the merges (including the SSL one). Would you be willing to test this again for me?

**Comment by justmobilize** [comment]
I apologize for the hard review. With moving a few things at the top, it isn't a simple white space change with it going into the class. I promise I didn't change anything.

**Review by anecdata — COMMENTED** [review]
Re-tested with https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/pull/11#pullrequestreview-2027291082. Good to go pending any others with code review.

**Comment by dhalbert** [comment]
Same q I asked re ESP32SPI. If this is an incompatible change, then we'll need to change any Guide examples we have. If not, no problem.

**Pull request merged**
