### PR TITLE
Fixed cyclic import

### PR DESCRIPTION
**Pull request by dherrada**

### CODE REVIEW

**Comment by ladyada** [comment]
did ya test this with hardware?

**Comment by dherrada** [comment]
I didn't

**Comment by ladyada** [comment]
yah plz

**Comment by dherrada** [comment]
@ladyada I don't actually have the hardware to test. I can order it if you'd like me to or we could just have someone that does have the hardware already test it.

**Comment by ladyada** [comment]
@brentru can u test when you're around next plz

**Comment by anecdata** [comment]
I think there might be an issue with `adafruit_bus_device`. Even before trying the PR, I couldn't get the released version to work with current libraries on 6.2.0-beta.4 or 6.1.0. Backed up to 5.3.1 and old libraries from that time, and that worked.

**Review by brentru — APPROVED** [review]
Following @anecdata  - I noted that the latest version of the `adafruit_requests` library has an issue with this library. However, that isn't related to this specific PR.

To isolate this PR from the issue with `requests` - I tested this pull request using an older library bundle but with the latest circuitpython version (`Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit Feather M4 Express with samd51j19`):

```code.py output:
Wiznet5k WebClient Test
Chip Version: w5500
MAC Address: ['0xde', '0xad', '0xbe', '0xef', '0xfe', '0xed']
My IP address is: 192.168.1.175
IP lookup adafruit.com: 104.20.38.240
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
This is a test of Adafruit WiFi!
If you can read this, its working :)

----------------------------------------

Fetching json from http://api.coindesk.com/v1/bpi/currentprice/USD.json
----------------------------------------
{'time': {'updated': 'Mar 26, 2021 14:48:00 UTC', 'updatedISO': '2021-03-26T14:48:00+00:00', 'updateduk': 'Mar 26, 2021 at 14:48 GMT'}, 'disclaimer': 'This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org', 'bpi': {'USD': {'code': 'USD', 'description': 'United States Dollar', 'rate_float': 53330.1, 'rate': '53,330.0883'}}}
----------------------------------------
Done!

Code done running.
```

This code is OK to merge in, however, @anecdata  do you want to open a new pull request within `adafruit_requests` or on this repo to address the issue with this library and requests?

**Comment by brentru** [comment]
@dherrada  Was this pull request in reference to a specific issue/forum post?

**Comment by dherrada** [comment]
@brentru I don't think so. I'm pretty sure I was just going through the libraries that were failing their pylint checks.

**Pull request merged**
