### PR TITLE
Refactor wiznet5k

### PR DESCRIPTION
**Pull request by BiffoBear**
Refactored WIZNET5K in preparation for implementing the W6100 chip and adding support for the Adafruit HTTP server (replacing the Wiznet5K WSGI module).
No change in functionality, but increased DNS timeout due to my loooooong ping Internet connection and some errors have been changed from returning an `int` from a function to raising an exception (a step on the way to HTTP server support).
Tested with `wiznet5k_simpletest.py` and `wiznet5k_simpleserver.py` on W5100s and W5500. Also calls to `ifconfig`, `unpretty_ip()`, `pretty_ip()`, `pretty_mac()`, `chip` and `link_status`

### CODE REVIEW

**Comment by FoamyGuy** [comment]
@BiffoBear can you merge main and resolve the conflicts if possible? I can test this out afterward.

**Comment by BiffoBear** [comment]
> @BiffoBear can you merge main and resolve the conflicts if possible? I can test this out afterward. 
Will do

**Comment by BiffoBear** [comment]
> @BiffoBear can you merge main and resolve the conflicts if possible? I can test this out afterward.

OK, that's done

**Comment by BiffoBear** [comment]
Closing this PR because I've finished implementing IPv4 support for w6100 chip elsewhere.

**Pull request closed without merging**
