### PR TITLE
Shorter socket exit timeout

### PR DESCRIPTION
**Pull request by BiffoBear**
#closes 89, 90 Decreased `socket.socket.__exit__` timeout from 1000 seconds to 19 seconds to match the Wiznet5k hardware defaults.

### CODE REVIEW

**Comment by dhalbert** [comment]
> I don't think this'll close #89, but it does look good to me for #90. I filed them as separate issues because I think they're different problems.

@BiffoBear Do you have a comment on this?

**Comment by BiffoBear** [comment]
> > I don't think this'll close #89, but it does look good to me for #90. I filed them as separate issues because I think they're different problems.
> 
> @BiffoBear Do you have a comment on this?

Good point well made. The documents are a little ambiguous, so I've gone through the C source code from the Wiznet drivers.

`socket.__exit__()` now follows the logic of the Wiznet driver for disconnecting and closing. I've taken the opportunity to remove calls to deprecated `socket.socket()` methods, as they just call the `WIZNET5K` methods anyway.

Cheers,
Martin

**Comment by BiffoBear** [comment]
But please note that the default hardware timeout for a TCP socket is about 19 seconds.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. I tested this version successfully with the simpleserver / client and simpletest requests examples on Feather ESP232-S2 TFT.

Thank you @BiffoBear

**Pull request merged**
